[workspace]
resolver = "2"
members = [
  "crates/inode",
  "crates/inode-core",
  "crates/inode-openconnect-sys",
  "crates/inode-routectl",
  "crates/inode-vpnd",
]
default-members = ["crates/inode", "crates/inode-vpnd", "crates/inode-routectl"]

[workspace.package]
version = "1.0.0"
edition = "2021"
rust-version = "1.75"
publish = false

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }
inode-core = { path = "crates/inode-core" }
inode-openconnect-sys = { path = "crates/inode-openconnect-sys" }
libc = "0.2"
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
thiserror = "2.0"
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "macros", "signal"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

[profile.release]
lto = "thin"
strip = true
